---
language: ruby

services:
  - docker

sudo: required

gemfile: test/integration/Gemfile

script:
  - bundle exec kitchen test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/